---
language: python
python: "2.7"
services: docker

sudo: true

env:
  global:
    - ROLE_NAME: iac-ansible-k8s
    - ANSIBLE_ACTION_WARNINGS: False
    - ANSIBLE_COMMAND_WARNINGS: False
    - ANSIBLE_DEPRECATION_WARNINGS: False
    - ANSIBLE_SYSTEM_WARNINGS: False
    - ANSIBLE_HOST_KEY_CHECKING: False

  - distribution: centos
    version: 7

addons:
 apt:
 packages:
 - python-pip

install:
 - pip install ansible
 - ansible --version
 - printf '[defaults]\nroles_path=../' >ansible.cfg
 - ansible-galaxy install wluisaraujo.iac_ansible_k8s
script:
  - mv wluisaraujo.iac_ansible_k8s  iac-ansible-k8s
# - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
# - ansible-playbook -i tests/inventory tests/test.yml --connection=local --check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...