---
# tasks file for k8s
- assert:
    msg: "This role can only be applied to RedHat or CentOS Environment"
    that: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" or ansible_distribution == "Fedora"

- include_tasks: sysctl-{{ ansible_distribution }}.yml

- include_tasks: packages-{{ ansible_distribution }}.yml

- include_tasks: prerequisites-{{ ansible_distribution }}.yml

#- include_tasks: setting-docker-{{ ansible_distribution }}.yml

- include_tasks: setting-k8s-{{ ansible_distribution }}.yml

## setting helm:  https://get.helm.sh/helm-v2.14.2-linux-amd64.tar.gz
...