---
- yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - epel-release
    
- shell: yum-config-manager --enable "{{ item }}" > /dev/null 2>&1 
  loop:
    - "base"
    - "centos-opstools-testing"
    - "centos-qemu-ev"
    - "centos-release-opstools"
    - "centosplus"
    - "epel"
    - "epel-testing"
    - "extras"
    - "fasttrack"
    - "updates"
         
- yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - bash-completion
    - bash-completion-extras
    - ccze
    - chrony
    - cockpit
    - curl
    - device-mapper-persistent-datas
    - htop
    - kexec-tools 
    - lsof
    - lvm2 
    - rsync
    - tuned
    - tuned-profiles-atomic
    - vim
    - wget
    - yum-utils
  notify:
      - "Start chronyd"
      - "Start tuned"
      - "Stop firewalld"
      
- yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - '*'    
...