---
- shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- shell: dnf config-manager --set-enabled docker-ce-edge
- shell: dnf config-manager --set-enabled docker-ce-nightly
- shell: dnf config-manager --set-enabled fedora-cisco-openh264
- shell: dnf config-manager --set-enabled fedora-modular
- shell: dnf config-manager --set-enabled fedora
- shell: dnf config-manager --set-enabled updates-modular
- shell: dnf config-manager --set-enabled updates
- shell: dnf config-manager --set-enabled updates-testing-modular
- shell: dnf config-manager --set-enabled updates-testing

- package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - '*'
    - bash-completion
    #- bind-utils
    #- bridge-utils
    #- ccze
    - chrony
    - cockpit
    #- curl
    #- device-mapper-persistent-data 
    #- git 
    #- htop
    #- kexec-tools 
    - lsof
    #- lvm2
    #- net-tools 
    - ovirt-guest-agent
    #- psacct
    #- pyOpenSSL  
    #- rsync
    - tuned
    - tuned-profiles-atomic
    - vim
    - wget
    - dnf-utils
    - dnf-plugins-core
    - python2-pip
    - python3-pip
    - tzdata
...