---
- command: setenforce 0

- selinux:
    state: permissive

- replace:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    replace: 'SELINUX=permissive'
  
- replace:
    dest: /etc/logrotate.conf
    regexp: '^#compress'
    replace: 'compress'

- lineinfile:
    path: /etc/hosts
    state:  present
    line: "{{ item }}"
  loop:
    - "172.16.0.8    k8s.exemplo.com.br ck8s"
    - "172.16.0.80     sv-k8s-cfx02.exemplo.com.br sv-k8s-cfx02"
    - "172.16.0.81     sv-k8s-cfx03.exemplo.com.br sv-k8s-cfx03"

- replace:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.origem }}"
    replace: "{{ item.destino }}"
  with_items:
    - { origem: '#Port', destino: 'Port 22' }
    - { origem: '#PermitRootLogin', destino: 'PermitRootLogin yes' }
    - { origem: '#GSSAPIAuthentication', destino: 'GSSAPIAuthentication no' }
    - { origem: '#TCPKeepAlive', destino: 'TCPKeepAlive yes' }
    - { origem: '#UseDNS', destino: 'UseDNS no' }
    - { origem: 'Port', destino: 'Port 22' }
    - { origem: 'PermitRootLogin', destino: 'PermitRootLogin yes' }
    - { origem: 'GSSAPIAuthentication', destino: 'GSSAPIAuthentication no' }
    - { origem: 'TCPKeepAlive', destino: 'TCPKeepAlive yes' }
    - { origem: 'UseDNS', destino: 'Port 22' }#

- shell: "{{ item }}" 
  loop:
    - "chronyc -a sources > /dev/null 2>&1"
    - "timedatectl set-timezone America/Sao_Paulo"
    - "timedatectl set-ntp true"
    - "tuned-adm profile atomic-guest"
...