---
- lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
  loop:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_sh
    - ip_vs_wrr
    - nf_conntrack_ipv4

- modprobe:
    name: "{{ item }}"
    state: present    
  loop:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_sh
    - ip_vs_wrr
    - nf_conntrack_ipv4 

- yum_repository:
    name: Kubernetes
    description: Kubernetes YUM Repository
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: 1
    enabled: true

- yum: 
    name: "{{ item }}" 
    state: present 
    update_cache: yes
  loop:
    - kubelet
    - kubeadm

#- get_url:
#    url: https://get.helm.sh/helm-v2.14.2-linux-amd64.tar.gz
#    dest: /tmp
#     validate_certs: no

#- name: Fix kubelet CGROUP_ARGS
#  replace:
#    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
#    regexp: .*KUBELET_CGROUP_ARGS=.*
#    replace: Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"
#  become: true
  #notify:
  #- "Start kubelet"

# kubeadm config images pull  
...