---
- sysctl:
    name: '{{ item.name }}'
    state: present
    value: '{{ item.value }}'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: 'fs.file-max',value: '65535' }
    - { name: 'fs.suid_dumpable', value: '0' }
    - { name: 'kernel.nmi_watchdog', value: '0' }
    - { name: 'kernel.panic', value: '10' }
    - { name: 'kernel.pid_max', value: '65536' }  
    - { name: 'kernel.randomize_va_space', value: '2' } 
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_source_route', value: '0'  }
    - { name: 'net.ipv4.conf.all.log_martians', value: '1' } 
    - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'net.ipv6.conf.all.accept_ra', value: '0' }
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' } 
    - { name: 'vm.drop_caches', value: '3' }
    - { name: 'vm.swappiness', value: '0' }
...